version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4800:80"  # Access via http://localhost:4800
    restart: unless-stopped
