version: '3'
services:
  angular-app:
    # image: angular-app:latest
    container_name: angular-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Map port 4200 on host to port 80 in the container
    environment:
      - NODE_ENV=development
    restart: unless-stopped

networks:
  default:
    external:
      name: network

